In [23]:
import pandas as pd

In [24]:
# Import FinnSentiment-1.1.tsv using polars
df = pd.read_csv('../data/finsen-v1-1-src/FinnSentiment-1.1.tsv', sep='\t', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1,0,1,1,4,-1.0,-1.0,0.0,NaN,NaN,NaN,4.0,4.0,4.0,0,-1,1,1,comments2008c.vrt 2145269,- Tervetuloa skotlantiin...
1,0,1,0,0,4,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,0,-1,12,1,comments2011c.vrt 3247745,"...... No, oikein sopiva sattumaha se vaan oli..."
2,0,0,0,0,3,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,0,-1,14,1,comments2007c.vrt 3792960,40.
3,1,1,1,1,5,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,0,1,7,1,comments2010d.vrt 2351708,Kyseessä voi olla loppuelämäsi nainen.
4,1,1,1,1,5,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,0,1,12,1,comments2007d.vrt 1701675,Sinne vaan ocean clubiin iskemään!

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23872 entries, 0 to 23871
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       23872 non-null  int64
 1   1       23872 non-null  int64
 2   2       23872 non-null  int64
 3   3       23872 non-null  int64
 4   4       23872 non-null  int64
 5   5       892 non-null    float64
 6   6       892 non-null    float64
 7   7       892 non-null    float64
 8   8       439 non-null    float64
 9   9       439 non-null    float64
 10  10      439 non-null    float64
 11  11      464 non-null    float64
 12  12      464 non-null    float64
 13  13      464 non-null    float64
 14  14      23872 non-null  int64
 15  15      23872 non-null  int64
 16  16      23872 non-null  int64
 17  17      23872 non-null  int64
 18  18      23872 non-null  object
 19  19      23872 non-null  object
dtypes: float64(9), int64(9), object(2)
memory usage: 3.6+ MB

In [26]:
df = df[df[0] == df[1]]

In [27]:
df = df[df[1] == df[2]]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14962 entries, 2 to 23871
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       14962 non-null  int64
 1   1       14962 non-null  int64
 2   2       14962 non-null  int64
 3   3       14962 non-null  int64
 4   4       14962 non-null  int64
 5   5       555 non-null    float64
 6   6       555 non-null    float64
 7   7       555 non-null    float64
 8   8       0 non-null      float64
 9   9       0 non-null      float64
 10  10      0 non-null      float64
 11  11      295 non-null    float64
 12  12      295 non-null    float64
 13  13      295 non-null    float64
 14  14      14962 non-null  int64
 15  15      14962 non-null  int64
 16  16      14962 non-null  int64
 17  17      14962 non-null  int64
 18  18      14962 non-null  object
 19  19      14962 non-null  object
dtypes: float64(9), int64(9), object(2)
memory usage: 2.4+ MB

In [29]:
# Keep only columns at indices 3, 19, and 20
df_trimmed = df.iloc[:, [2, 19]]
df_trimmed.head(25)

    2                                                  19
2    0                                                40.
3    1             Kyseessä voi olla loppuelämäsi nainen.
4    1                 Sinne vaan ocean clubiin iskemään!
5    1  Itsekin pidän Keskustan kampanjointia ihan hyv...
6    0                            Kamppi, Kontula, Kluuvi
8   -1               en haluaisi että kissani vuotaa.. =)
9   -1                     Nyt olisi lääkitys paikallaan.
10   0  Ihmiset joutuvat joskus monenlaisien päätelmie...
11  -1  Eniten pelkään sitä, että jos mies vain koko a...
12   1  Muutenkin suosittelen kaikille asiasta kiinnos...
13   0  Koska naiset yleensä arvostavat miehessä enite...
16   0  Jos taas mielestäsi maailmassa on jokin pieles...
17  -1                   Tuntuu kuin olisin pelkkä huora.
18   0                     Miten on Turun-lentojen laits?
19   1        Tottakai myös ylpeä "tulevasta" vaimostani.
21   0  Tämähän ei maksa kaupungille mitään, mutta ope...
22  -1                Missä kohtaa olen sinua nimitellyt?
23   1  Suuret kiitokset tämän mahtavan tapahtuman jär...
24   0       on vapaaehtoista käyttääkö uikkareita vai ei
25   0  Tuolloin 6-10 suden *lauma* liikuskeli Orivede...
26   0  Tai voit vaikka katella leffoja makuuni.fi siv...
27   0      Missä sitä kouluttautuis ja mitä sitä tekisi.
29   1  Mulla on lapsi jota rakastan enemmän kuin mitä...
31  -1  Sateenkaariväki kuvittelee, että kaksi "isää" ...
33  -1                    Mikä Hämeenlinnalaisia vaivaa..

In [30]:
# Rename columns "2" and "19" to "label" and "text"
df_trimmed = df_trimmed.rename(columns={2: "label", 19: "text"})

In [31]:
label_map = {-1: 0, 0: 1, 1: 2}
df_trimmed["label"] = df_trimmed["label"].map(label_map)

In [32]:
# Save df_trimmed as a pickle file
df_trimmed.to_pickle('../data/finnsentiment_cleaned_unambiguous.pkl')

In [33]:
df_trimmed_pickle = pd.read_pickle('../data/finnsentiment_cleaned_unambiguous.pkl')
df_trimmed_pickle.head(25)

    label                                               text
2       1                                                40.
3       2             Kyseessä voi olla loppuelämäsi nainen.
4       2                 Sinne vaan ocean clubiin iskemään!
5       2  Itsekin pidän Keskustan kampanjointia ihan hyv...
6       1                            Kamppi, Kontula, Kluuvi
8       0               en haluaisi että kissani vuotaa.. =)
9       0                     Nyt olisi lääkitys paikallaan.
10      1  Ihmiset joutuvat joskus monenlaisien päätelmie...
11      0  Eniten pelkään sitä, että jos mies vain koko a...
12      2  Muutenkin suosittelen kaikille asiasta kiinnos...
13      1  Koska naiset yleensä arvostavat miehessä enite...
16      1  Jos taas mielestäsi maailmassa on jokin pieles...
17      0                   Tuntuu kuin olisin pelkkä huora.
18      1                     Miten on Turun-lentojen laits?
19      2        Tottakai myös ylpeä "tulevasta" vaimostani.
21      1  Tämähän ei maksa kaupungille mitään, mutta ope...
22      0                Missä kohtaa olen sinua nimitellyt?
23      2  Suuret kiitokset tämän mahtavan tapahtuman jär...
24      1       on vapaaehtoista käyttääkö uikkareita vai ei
25      1  Tuolloin 6-10 suden *lauma* liikuskeli Orivede...
26      1  Tai voit vaikka katella leffoja makuuni.fi siv...
27      1      Missä sitä kouluttautuis ja mitä sitä tekisi.
29      2  Mulla on lapsi jota rakastan enemmän kuin mitä...
31      0  Sateenkaariväki kuvittelee, että kaksi "isää" ...
33      0                    Mikä Hämeenlinnalaisia vaivaa..