In [10]:
import polars as pl
import pandas as pd

In [12]:
# Import FinnSentiment-1.1.tsv using polars
df = pd.read_csv('../data/finsen-v1-1-src/FinnSentiment-1.1.tsv', sep='\t')
df.head()

,1,0,1.1,1.2,4,-1,-1.1,0.1,Unnamed: 8,Unnamed: 9,Unnamed: 10,4.1,4.2,4.3,0.2,-1.2,1.3,1.4,comments2008c.vrt 2145269,- Tervetuloa skotlantiin...
0,0,1,0,0,4,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,0,-1,12,1,comments2011c.vrt 3247745,"...... No, oikein sopiva sattumaha se vaan oli..."
1,0,0,0,0,3,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,0,-1,14,1,comments2007c.vrt 3792960,40.
2,1,1,1,1,5,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,0,1,7,1,comments2010d.vrt 2351708,Kyseessä voi olla loppuelämäsi nainen.
3,1,1,1,1,5,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,0,1,12,1,comments2007d.vrt 1701675,Sinne vaan ocean clubiin iskemään!
4,1,1,1,1,5,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0,0,16,1,comments2010c.vrt 600831,Itsekin pidän Keskustan kampanjointia ihan hyv...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23871 entries, 0 to 23870
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   1                            23871 non-null  int64
 1   0                            23871 non-null  int64
 2   1.1                          23871 non-null  int64
 3   1.2                          23871 non-null  int64
 4   4                            23871 non-null  int64
 5   -1                           891 non-null    float64
 6   -1.1                         891 non-null    float64
 7   0.1                          891 non-null    float64
 8   Unnamed: 8                   439 non-null    float64
 9   Unnamed: 9                   439 non-null    float64
 10  Unnamed: 10                  439 non-null    float64
 11  4.1                          463 non-null    float64
 12  4.2                          463 non-null    float64
 13  4.3                          463 non-null    float64
 14  0.2                          23871 non-null  int64
 15  -1.2                         23871 non-null  int64
 16  1.3                          23871 non-null  int64
 17  1.4                          23871 non-null  int64
 18  comments2008c.vrt 2145269    23871 non-null  object
 19  - Tervetuloa skotlantiin...  23871 non-null  object
dtypes: float64(9), int64(9), object(2)
memory usage: 3.6+ MB

In [17]:
# Keep only columns at indices 3, 19, and 20
df_trimmed = df.iloc[:, [2, 19]]
df_trimmed.head(25)

    1.1                        - Tervetuloa skotlantiin...
0     0  ...... No, oikein sopiva sattumaha se vaan oli...
1     0                                                40.
2     1             Kyseessä voi olla loppuelämäsi nainen.
3     1                 Sinne vaan ocean clubiin iskemään!
4     1  Itsekin pidän Keskustan kampanjointia ihan hyv...
5     0                            Kamppi, Kontula, Kluuvi
6     0                        huomista päivää odotellen..
7    -1               en haluaisi että kissani vuotaa.. =)
8    -1                     Nyt olisi lääkitys paikallaan.
9     0  Ihmiset joutuvat joskus monenlaisien päätelmie...
10   -1  Eniten pelkään sitä, että jos mies vain koko a...
11    1  Muutenkin suosittelen kaikille asiasta kiinnos...
12    0  Koska naiset yleensä arvostavat miehessä enite...
13    1                    Teillähän asenne on kohdallaan!
14    1  Ja kun vielä nuukan puoleinenkin on, mikäs sen...
15    0  Jos taas mielestäsi maailmassa on jokin pieles...
16   -1                   Tuntuu kuin olisin pelkkä huora.
17    0                     Miten on Turun-lentojen laits?
18    1        Tottakai myös ylpeä "tulevasta" vaimostani.
19   -1           en kertonut, koska oisit vaan suuttunut.
20    0  Tämähän ei maksa kaupungille mitään, mutta ope...
21   -1                Missä kohtaa olen sinua nimitellyt?
22    1  Suuret kiitokset tämän mahtavan tapahtuman jär...
23    0       on vapaaehtoista käyttääkö uikkareita vai ei
24    0  Tuolloin 6-10 suden *lauma* liikuskeli Orivede...

In [24]:
# Drop index and save to a new CSV file
df_trimmed.to_csv('../data/finnsentiment_cleaned.csv', index=False)

In [26]:
# Save df_trimmed as a pickle file
df_trimmed.to_pickle('../data/finnsentiment_cleaned.pkl')

In [27]:
df_trimmed_pickle = pd.read_pickle('../data/finnsentiment_cleaned.pkl')
df_trimmed_pickle.head(25)

    1.1                        - Tervetuloa skotlantiin...
0     0  ...... No, oikein sopiva sattumaha se vaan oli...
1     0                                                40.
2     1             Kyseessä voi olla loppuelämäsi nainen.
3     1                 Sinne vaan ocean clubiin iskemään!
4     1  Itsekin pidän Keskustan kampanjointia ihan hyv...
5     0                            Kamppi, Kontula, Kluuvi
6     0                        huomista päivää odotellen..
7    -1               en haluaisi että kissani vuotaa.. =)
8    -1                     Nyt olisi lääkitys paikallaan.
9     0  Ihmiset joutuvat joskus monenlaisien päätelmie...
10   -1  Eniten pelkään sitä, että jos mies vain koko a...
11    1  Muutenkin suosittelen kaikille asiasta kiinnos...
12    0  Koska naiset yleensä arvostavat miehessä enite...
13    1                    Teillähän asenne on kohdallaan!
14    1  Ja kun vielä nuukan puoleinenkin on, mikäs sen...
15    0  Jos taas mielestäsi maailmassa on jokin pieles...
16   -1                   Tuntuu kuin olisin pelkkä huora.
17    0                     Miten on Turun-lentojen laits?
18    1        Tottakai myös ylpeä "tulevasta" vaimostani.
19   -1           en kertonut, koska oisit vaan suuttunut.
20    0  Tämähän ei maksa kaupungille mitään, mutta ope...
21   -1                Missä kohtaa olen sinua nimitellyt?
22    1  Suuret kiitokset tämän mahtavan tapahtuman jär...
23    0       on vapaaehtoista käyttääkö uikkareita vai ei
24    0  Tuolloin 6-10 suden *lauma* liikuskeli Orivede...